<a href="https://colab.research.google.com/github/munothk28/munothk28/blob/main/Copy_of_happiness_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Display country showing highest happiness score by using sorting from pandas liberary.

In [ ]:

#highest happiness score country

import pandas as pd
def get_data():
  url='https://github.com/munothk28/munothk28/blob/main/Happiness_dataset.xlsx?raw=true'
  happiness = pd.read_excel(url)
  sorted_rank1=happiness.sort_values("Happiness Score", ascending = False).head(1)
  display(sorted_rank1)

  
get_data()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738

display lowest happiness score country.

In [ ]:
#lowest happiness score country
import pandas as pd
def get_data():
  url='https://github.com/munothk28/munothk28/blob/main/Happiness_dataset.xlsx?raw=true'
  happiness = pd.read_excel(url)
  sorted_rank1=happiness.sort_values("Happiness Score").head(1)
  display(sorted_rank1)
get_data()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

Arranging all the rows in Ascending order on by considering the value of economy(GDP per capita) and health(Life Expectancy).

In [ ]:
#sorting rows by Economy and Health in ascending order
import pandas as pd
def get_region():
  url=  'https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true'
  happiness = pd.read_excel(url)
  sort=happiness.sort_values(by =["Economy (GDP per Capita)","Health (Life Expectancy)"])
  
  return sort
get_region()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
119,Congo (Kinshasa),Sub-Saharan Africa,120.0,4.517,0.03680,0.00000,1.00120,0.09806,0.22605,0.07625,0.24834,2.86712
156,Burundi,Sub-Saharan Africa,157.0,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
130,Malawi,Sub-Saharan Africa,131.0,4.292,0.06130,0.01604,0.41134,0.22562,0.43054,0.06977,0.33128,2.80791
143,Niger,Sub-Saharan Africa,144.0,3.845,0.03602,0.06940,0.77265,0.29707,0.47692,0.15639,0.19387,1.87877
115,Liberia,Sub-Saharan Africa,116.0,4.571,0.11068,0.07120,0.78968,0.34201,0.28531,0.06232,0.24362,2.77729
...,...,...,...,...,...,...,...,...,...,...,...,...
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
23,Singapore,Southeastern Asia,24.0,6.798,0.03780,1.52186,1.02000,1.02525,0.54252,0.49210,0.31105,1.88501
38,Kuwait,Middle East and Northern Africa,39.0,6.295,0.04456,1.55422,1.16594,0.72492,0.55499,0.25609,0.16228,1.87634
16,Luxembourg,Western Europe,17.0,6.946,0.03499,1.56391,1.21963,0.91894,0.61583,0.37798,0.28034,1.96961
27,Qatar,Middle East and Northern Africa,28.0,6.611,0.06257,1.69042,1.07860,0.79733,0.64040,0.52208,0.32573,1.55674

showing correlation between different columns.

In [ ]:
# correlation between different factors and happiness
import numpy as np
import pandas as pd
url='https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true'
df=pd.read_excel(url)
df.corr()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
Happiness Rank,1.000000,-0.992105,0.158516,-0.785267,-0.733644,-0.735613,-0.556886,-0.372315,-0.160142,-0.521999
Happiness Score,-0.992105,1.000000,-0.177254,0.780966,0.740605,0.724200,0.568211,0.395199,0.180319,0.530474
Standard Error,0.158516,-0.177254,1.000000,-0.217651,-0.120728,-0.310287,-0.129773,-0.178325,-0.088439,0.083981
Economy (GDP per Capita),-0.785267,0.780966,-0.217651,1.000000,0.645299,0.816478,0.370300,0.307885,-0.010465,0.040059
Family,-0.733644,0.740605,-0.120728,0.645299,1.000000,0.531104,0.441518,0.205605,0.087513,0.148117
Health (Life Expectancy),-0.735613,0.724200,-0.310287,0.816478,0.531104,1.000000,0.360477,0.248335,0.108335,0.018979
Freedom,-0.556886,0.568211,-0.129773,0.370300,0.441518,0.360477,1.000000,0.493524,0.373916,0.062783
Trust (Government Corruption),-0.372315,0.395199,-0.178325,0.307885,0.205605,0.248335,0.493524,1.000000,0.276123,-0.033105
Generosity,-0.160142,0.180319,-0.088439,-0.010465,0.087513,0.108335,0.373916,0.276123,1.000000,-0.101301
Dystopia Residual,-0.521999,0.530474,0.083981,0.040059,0.148117,0.018979,0.062783,-0.033105,-0.101301,1.000000

Identifying coorelation between different columns in dataframe 
1. Happiness score with economy(GDP per cpita)

In [7]:
import pandas as pd 
import numpy as np
def correlation():
  url='https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true'
  df=pd.read_excel(url)
  col1, col2 = "Happiness Score", "Economy (GDP per Capita)"
  corr = df[col1].corr(df[col2])
  print ("Correlation between ", col1, " and ", col2, "is: ", round(corr, 2))
correlation()

Correlation between  Happiness Score  and  Economy (GDP per Capita) is:  0.78

2. correlation between Happiness score and Health (Life Expectancy)

In [8]:
import pandas as pd 
import numpy as np
def correlation():
  url='https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true'
  df=pd.read_excel(url)
  col1, col2 = "Happiness Score", "Health (Life Expectancy)"
  corr = df[col1].corr(df[col2])
  print ("Correlation between ", col1, " and ", col2, "is: ", round(corr, 2))
correlation()

Correlation between  Happiness Score  and  Health (Life Expectancy) is:  0.72

3. correlation between Happiness score and Freedom

In [9]:
import pandas as pd 
import numpy as np
def correlation():
  url='https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true'
  df=pd.read_excel(url)
  col1, col2 = "Happiness Score", "Freedom"
  corr = df[col1].corr(df[col2])
  print ("Correlation between ", col1, " and ", col2, "is: ", round(corr, 2))
correlation()

Correlation between  Happiness Score  and  Freedom is:  0.57

4. correlation between Happiness score and Trust (Government Corruption)

In [10]:
import pandas as pd 
import numpy as np
def correlation():
  url='https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true'
  df=pd.read_excel(url)
  col1, col2 = "Happiness Score", "Trust (Government Corruption)"
  corr = df[col1].corr(df[col2])
  print ("Correlation between ", col1, " and ", col2, "is: ", round(corr, 2))
correlation()

Correlation between  Happiness Score  and  Trust (Government Corruption) is:  0.4

5. correlation between Economy (GDP per Capita) and Health (Life Expectancy)

In [12]:
import pandas as pd 
import numpy as np
def correlation():
  url='https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true'
  df=pd.read_excel(url)
  col1, col2 = "Economy (GDP per Capita)", "Health (Life Expectancy)"
  corr = df[col1].corr(df[col2])
  print ("Correlation between ", col1, " and ", col2, "is: ", round(corr, 2))
correlation()

Correlation between  Economy (GDP per Capita)  and  Health (Life Expectancy) is:  0.82

correlation between total of  Economy (GDP per Capita) and  Health (Life Expectancy) with Happiness score.

In [19]:
import pandas as pd 
import numpy as np
def add_column():
  df=pd.read_excel('https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true')
  df1=pd.read_excel('https://github.com/munothk28/munothk28/blob/main/2015%20(3).xlsx?raw=true')
  df2 = df.append(df1,ignore_index=True)
  return df2
    
add_column()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Total
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,NaN
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,NaN
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,NaN
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,NaN
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,Rwanda,Sub-Saharan Africa,154.0,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042,0.65072
312,Benin,Sub-Saharan Africa,155.0,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328,0.60575
313,Syria,Middle East and Northern Africa,156.0,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858,1.38513
314,Burundi,Sub-Saharan Africa,157.0,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302,0.23926
315,Togo,Sub-Saharan Africa,158.0,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726,0.49311

In [21]:
def correlation():
  df2=pd.read_excel('https://github.com/munothk28/munothk28/blob/main/2015%20(3).xlsx?raw=true')
  col1, col2 = "Happiness Score", "Total"
  corr = df2[col1].corr(df2[col2])
  print ("Correlation between ", col1, " and ", col2, "is: ", round(corr, 2))
correlation()

Correlation between  Happiness Score  and  Total is:  0.79