<a href="https://colab.research.google.com/github/munothk28/munothk28/blob/main/happiness_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:

#highest happiness score country

import pandas as pd
def get_data():
  url='https://github.com/munothk28/munothk28/blob/main/Happiness_dataset.xlsx?raw=true'
  happiness = pd.read_excel(url)
  sorted_rank1=happiness.sort_values("Happiness Score", ascending = False).head(1)
  display(sorted_rank1)

  
get_data()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738

In [27]:
#lowest happiness score country
import pandas as pd
def get_data():
  url='https://github.com/munothk28/munothk28/blob/main/Happiness_dataset.xlsx?raw=true'
  happiness = pd.read_excel(url)
  sorted_rank1=happiness.sort_values("Happiness Score").head(1)
  display(sorted_rank1)
get_data()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [30]:
#sorting rows by Economy and Health in ascending order
import pandas as pd
def get_region():
  url=  'https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true'
  happiness = pd.read_excel(url)
  sort=happiness.sort_values(by =["Economy (GDP per Capita)","Health (Life Expectancy)"])
  
  return sort
get_region()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
119,Congo (Kinshasa),Sub-Saharan Africa,120.0,4.517,0.03680,0.00000,1.00120,0.09806,0.22605,0.07625,0.24834,2.86712
156,Burundi,Sub-Saharan Africa,157.0,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
130,Malawi,Sub-Saharan Africa,131.0,4.292,0.06130,0.01604,0.41134,0.22562,0.43054,0.06977,0.33128,2.80791
143,Niger,Sub-Saharan Africa,144.0,3.845,0.03602,0.06940,0.77265,0.29707,0.47692,0.15639,0.19387,1.87877
115,Liberia,Sub-Saharan Africa,116.0,4.571,0.11068,0.07120,0.78968,0.34201,0.28531,0.06232,0.24362,2.77729
...,...,...,...,...,...,...,...,...,...,...,...,...
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
23,Singapore,Southeastern Asia,24.0,6.798,0.03780,1.52186,1.02000,1.02525,0.54252,0.49210,0.31105,1.88501
38,Kuwait,Middle East and Northern Africa,39.0,6.295,0.04456,1.55422,1.16594,0.72492,0.55499,0.25609,0.16228,1.87634
16,Luxembourg,Western Europe,17.0,6.946,0.03499,1.56391,1.21963,0.91894,0.61583,0.37798,0.28034,1.96961
27,Qatar,Middle East and Northern Africa,28.0,6.611,0.06257,1.69042,1.07860,0.79733,0.64040,0.52208,0.32573,1.55674